### ISSUE TITLE
queue.solve it please

### ISSUE THREAD

**Issue by Lowkik-Sai** [zhycorp/music-bot-example#47]
2020-10-02T10:11:16.132292+00:00 app[web.1]: Unhandled Rejection at:  Promise {
2020-10-02T10:11:16.132314+00:00 app[web.1]:   <rejected> TypeError: Cannot read property 'queue' of undefined
2020-10-02T10:11:16.132315+00:00 app[web.1]:       at Client.<anonymous> (/app/index.js:510:46)
2020-10-02T10:11:16.132315+00:00 app[web.1]:       at Client.emit (events.js:327:22)
2020-10-02T10:11:16.132316+00:00 app[web.1]:       at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
2020-10-02T10:11:16.132317+00:00 app[web.1]:       at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2020-10-02T10:11:16.132317+00:00 app[web.1]:       at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
2020-10-02T10:11:16.132318+00:00 app[web.1]:       at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
2020-10-02T10:11:16.132318+00:00 app[web.1]:       at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
2020-10-02T10:11:16.132319+00:00 app[web.1]:       at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:125:16)
2020-10-02T10:11:16.132319+00:00 app[web.1]:       at WebSocket.emit (events.js:315:20)
2020-10-02T10:11:16.132320+00:00 app[web.1]:       at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:797:20)
2020-10-02T10:11:16.132320+00:00 app[web.1]: } reason:  TypeError: Cannot read property 'queue' of undefined
2020-10-02T10:11:16.132320+00:00 app[web.1]:     at Client.<anonymous> (/app/index.js:510:46)
2020-10-02T10:11:16.132321+00:00 app[web.1]:     at Client.emit (events.js:327:22)
2020-10-02T10:11:16.132321+00:00 app[web.1]:     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
2020-10-02T10:11:16.132321+00:00 app[web.1]:     at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2020-10-02T10:11:16.132322+00:00 app[web.1]:     at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
2020-10-02T10:11:16.132322+00:00 app[web.1]:     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
2020-10-02T10:11:16.132323+00:00 app[web.1]:     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
2020-10-02T10:11:16.132323+00:00 app[web.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:125:16)
2020-10-02T10:11:16.132323+00:00 app[web.1]:     at WebSocket.emit (events.js:315:20)
2020-10-02T10:11:16.132325+00:00 app[web.1]:     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:797:20)

**Comment by mozartrafi** [comment]
What you have did into  file?

**Comment by mozartrafi** [comment]
What you have did into index.js file?

**Comment by mozartrafi** [comment]
Or, did you mean the error appears at queue command? let's talk to @Tiramitzu then

**Comment by mozartrafi** [comment]
Alright
